Repository Dova-Khing/La-ultima-apuesta, pull requests merged in 2025-08, with the labels that each got.

#1 Clases que contendrán nuestro sistema Casino
  Clases/Bingo.py
  Clases/Loteria.py
  Clases/Ruleta.py
  Clases/Usuario.py
  main.py
Labels: enhancement

#4 Esqueleto que contendra nuestro casino
  Clases/Bingo.py
  Clases/Loteria.py
  Clases/Ruleta.py
  Clases/Usuario.py
  main.py
Labels: enhancement

#6 menu realizado en main
  main.py
Labels: enhancement

#7 Feat creacion usuario bingo
  Clases/Bingo.py
  Clases/Loteria.py
  Clases/Ruleta.py
  Clases/Usuario.py
Labels: enhancement

#9 Ya paso la verificacion en Dev, por fa subirlo
  Clases/Bingo.py
  Clases/Loteria.py
  Clases/Ruleta.py
  Clases/Usuario.py
  main.py
Labels: enhancement

#10 Feat agregar comentarios
  Clases/Bingo.py
  Clases/Loteria.py
  Clases/Ruleta.py
Labels: documentation, enhancement

#15 Dev
  Clases/Bingo.py
  Clases/Loteria.py
  Clases/Ruleta.py
  Clases/Usuario.py
  Clases/__pycache__/Bingo.cpython-312.pyc
  Clases/__pycache__/Loteria.cpython-312.pyc
  Clases/__pycache__/Ruleta.cpython-312.pyc
  Clases/__pycache__/Usuario.cpython-312.pyc
  main.py
Labels: enhancement

#18 Dev
  Clases/Bingo.py
  Clases/Loteria.py
  Clases/Ruleta.py
  Clases/Usuario.py
  Clases/Validaciones.py
  Clases/__pycache__/Bingo.cpython-312.pyc
  Clases/__pycache__/Loteria.cpython-312.pyc
  Clases/__pycache__/Ruleta.cpython-312.pyc
  Clases/__pycache__/Usuario.cpython-312.pyc
  Clases/__pycache__/Validaciones.cpython-312.pyc
  main.py
Labels: enhancement

#17 Dev
  Clases/Usuario.py
  Clases/Validaciones.py
  Clases/__pycache__/Bingo.cpython-312.pyc
  Clases/__pycache__/Loteria.cpython-312.pyc
  Clases/__pycache__/Ruleta.cpython-312.pyc
  Clases/__pycache__/Usuario.cpython-312.pyc
  Clases/__pycache__/Validaciones.cpython-312.pyc
  main.py
Labels: enhancement

#19 feat:correcion-de-errores
  Clases/Usuario.py
  main.py
Labels: bug

#21 Feat agregar md y solucion ruleta
  Clases/Bingo.py
  Clases/Ruleta.py
  Clases/Usuario.py
  Clases/Validaciones.py
  README.md
  main.py
Labels: documentation, enhancement

#25 feat:Corregio-cambiado-concretado
  Clases/Bingo.py
  Clases/Loteria.py
  Clases/Usuario.py
  Clases/Validaciones.py
  main.py
Labels: bug, documentation, enhancement

#27 Feat correcion
  Clases/Bingo.py
  Clases/Ruleta.py
  Clases/Usuario.py
Labels: enhancement
